# Generated by Django 6.0.3 on 2026-04-30 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evalify_app', '0014_escar_action_plans'),
        ('evalify_app', '0015_escar_action_plans'),
    ]

    operations = [
    ]
