# Generated by Django 6.0.3 on 2026-04-30 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evalify_app', '0016_merge_0014_escar_action_plans_0015_escar_action_plans'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='grace_period_hours',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='late_deduction_value',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='max_late_days',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pastpaper',
            name='allowed_courses',
            field=models.ManyToManyField(blank=True, help_text='If not public, only students in these courses can access', related_name='past_papers', to='evalify_app.course'),
        ),
        migrations.AlterField(
            model_name='pastpaper',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='pastpaper',
            name='is_public',
            field=models.BooleanField(default=False, help_text='True = all enrolled students can access'),
        ),
        migrations.AlterField(
            model_name='pastpaperquestion',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='pastpaperquestion',
            name='paper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='evalify_app.pastpaper'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='final_score',
            field=models.FloatField(default=0),
        ),
    ]
