# Generated by Django 5.2.4 on 2026-05-03 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evalify_app', '0017_add_course_is_archived'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('faculty', 'Faculty'), ('student', 'Student'), ('admin', 'Admin'), ('doa', 'DOA')], default='', max_length=20),
        ),
    ]
