# Generated by Django 6.0.3 on 2026-05-11 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evalify_app', '0023_headmaster_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notif_type',
            field=models.CharField(choices=[('grade_released', 'Grade Released'), ('deadline_tomorrow', 'Deadline Tomorrow'), ('deadline_today', 'Due Today'), ('new_assignment', 'New Assignment'), ('new_material', 'New Material'), ('announcement', 'Announcement'), ('plo_feedback', 'PLO Feedback'), ('plo_alert', 'PLO Alert')], max_length=30),
        ),
    ]
